name: JavaScript in Browser Homeworks

on:
  push:
    branches: [ "main" ]

env:
  HOME_URL: 'https://danbzay.github.io/js-browser/'
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - page-path: '2-DOM/hit-game/'
            page-name: 'hit-game'  
            node-version: 22.x
          - page-path: '2-DOM/loading-sorting/'
            page-name: 'loading-sorting'
            node-version: 22.x

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Save old version if page actual
      id: old_page
      run: |  
        regex_page_path=$(echo "${{ matrix.page-path }}" | sed 's/[.\/]/\\&/g')
        git show --dirstat HEAD --name-only       
        git show --dirstat --name-only HEAD | grep -e $regex_page_path -e workflows || 
          ((echo 'grep status='$?; wget -r -np -P ${{ matrix.page-path }}dist $HOME_URL${{ matrix.page-name }}) &&
          (echo 'wget status='$?; echo 'saved=true' >> $GITHUB_OUTPUT))

    - name: Use Node.js ${{ matrix.node-version }}
      if: ${{steps.old_page.outputs.saved != true }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
   
    - name: Build
      if: ${{steps.old_page.outputs.saved != true }}
      run: |
        echo 'saved='${{ steps.old_page.outputs.saved }}
        cd ${{ matrix.page-path }}        
        npm install
        npx eslint
        npx webpack

    - name: Upload Page Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ matrix.page-path }}dist 
        name: ${{ matrix.page-name }}

  combine:
    runs-on: ubuntu-latest
    needs: build
   
    steps:
    - name: Download and Combine Pages
      uses: actions/download-artifact@v5

    - name: Create home index.html
      run: |
        echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">' > index.html
        echo '<title>JS in Browser HomeWorks</title></head><body><ul>' >> index.html
        ls -d */ | sed 's/\///g' > dirlist
        cat dirlist
        sed -E 's/((^.*?$))/<li><a href="\1">\1<\/a><\/li>/g' dirlist >> index.html
        echo '</ul></body></html>' >> index.html 
        cat index.html
        rm dirlist
        
    - name: Display structure of files
      run: ls -R

    - name: Upload Combined Pages Artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ github.workspace }}      
          
  deploy:
    runs-on: ubuntu-latest
    needs: combine
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Display structure of files
      run: ls -R
            
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
